pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = "/go/cache"
                GOMODCACHE = "/go/mod"
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'mkdir -p $GOCACHE $GOMODCACHE'
                    sh 'chmod -R 777 $GOCACHE $GOMODCACHE'
                    sh 'go mod download'
                    sh 'go test -v ./...'
                }
            }
        }
    }
}