pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = "/go/cache"
                GOMODCACHE = "/go/mod"
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p $GOCACHE $GOMODCACHE
                        chmod -R 777 $GOCACHE $GOMODCACHE
                        go mod download
                        go test -v ./...
                    '''
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
        }
    }
}